

# ============ Kuiper Platform
# NOTE: Kuiper IP and PORT will not be used anymore since gunicorn will handle the requests, see and change Gunicorn section instead 
Kuiper:
  IP            : 0.0.0.0         # flask web application ip    # deprecated since gunicorn will handle the sessions 
  PORT          : 5000            # flask web application port  # deprecated since gunicorn will handle the sessions 
  Debug         : False           # enable debugging mode       # deprecated since gunicorn will handle the sessions 
  RemoveRawFiles: True            # remove raw files uploaded to Kuiper, as consequences enable this will allow upload the file multiple times

# ============ Gunicorn configuration
# gunicorn used to support multi-request connections at the same time, gunicorn will run Flask platform and handle requests to it
Gunicorn:
  IP:           0.0.0.0           # gunicorn LISTEN IP address
  PORT:         8000              # gunicorn LISTEN PORT number


# ============ AdminLTE
adminlte:
  SIDEBAR_OPEN: False             # by default the left sidebar of platform closed


# ============ configuration of celery
CELERY:
  CELERY_BROKER_URL     : redis://localhost:6379
  CELERY_RESULT_BACKEND : redis://localhost:6379
  CELERY_TASK_ACKS_LATE : True

# ============ Elasticsearch
ElasticSearch:
  IP    : 0.0.0.0
  PORT  : 9200


# ============ MongoDB
MongoDB:
  DB_NAME: 'Kuiper'         # MongoDB Database name
  DB_IP: '127.0.0.1'        # MongoDB Database IP address 
  DB_PORT: 27017            # MongoDB Database Port number


# ============ Git
Git:
  git_url_release : 'https://api.github.com/repos/salehmuhaysin/Kuiper-1/releases/latest'                                     # link for git to pull new updates if exists
  k_version       : "v0.4.0"                                                                          # current version of kuiper


# ============ configuration of directories on the platform
# it is preferable to not change these settings (except platform_folder)  
Directories:
  platform_folder: &platform_folder   "./"                                 # main folder
  app_folder: &app_folder             [*platform_folder, /app]          # application files folder
  app_parsers:                        [*platform_folder, /app/parsers]  # parsers folder
  artifacts_upload:                   [*platform_folder, /files]        # uploaded artifacts folders  
  artifacts_upload_raw:               [*platform_folder, /raw]          # original uploaded compressed files


# ============ case_sidebar
# Title content: [<title on sidebar>,<url path>,<icon>]
# SubTitles: [ [ <title on sidebar>,<url path>,<icon>] , etc. ]
case_sidebar:
  - Title: ["Dashboard","/case/<case_id>/dashboard","fa fa-pie-chart"]
    SubTitles : Null
  - Title: ["Machines","/case/<case_id>","fa fa-laptop"]
    SubTitles : Null
  - Title: ["Artifacts","/case/<case_id>/browse_artifacts","fa  fa-cubes"]
    SubTitles : Null
  - Title: ["Timeline","/case/<case_id>/timeline","fa fa-clock-o"]
    SubTitles : Null
  - Title: ["Alerts","/case/<case_id>/alerts","fa  fa-bell"]
    SubTitles : Null

# ============ admin_sidebar
# Title content: [<title on sidebar>,<url path>,<icon>]
# SubTitles: [ [ <title on sidebar>,<url path>,<icon>] , etc. ]
admin_sidebar:
  - Title:      ["Cases","/admin/","fa  fa-globe"]
    SubTitles : Null
  - Title:      ['Rules' , '/admin/rules' , 'fa fa-list-alt']
    SubTitles : Null
  - Title:      ['Settings' , '#' , 'fa fa-gears' ]
    SubTitles : [
          ['Configuration' , '/admin/config' , 'fa fa-gears'],
          ['About' , '/admin/update' , 'fa fa-gears']
      ]
